In [1]:
from NCD import NCD
import utils
from Submission import Submission
from NCDClusterer import NCDClusterer
import os
from tokenizer import JavaTokenizer
import numpy as np

In [21]:
arr_set1=[r"C:\Users\vikram14\Desktop\Research\GradescopeFileSimilarities\set1\NewExpression.java",r"C:\Users\vikram14\Desktop\Research\GradescopeFileSimilarities\set1\NewCompositeExpression.java",
r"C:\Users\vikram14\Desktop\Research\GradescopeFileSimilarities\set1\ComplexExpression.java"]
students= [("a",1),("b",2),("c",3)]
subs=utils.fileNameArray_to_SubmissionArray(arr_set1,students)
utils.deleteFiles()
arr_set1_tok,arr_set1_stripped=utils.tokenizeFiles(arr_set1)

In [3]:
clusterer=NCDClusterer([],subs)

In [6]:
sigmoid(1-clusterer.checkBlockSimilarity(k=5,b=256,s=64))


array([[98.90130574, 97.65625603, 90.32836749],
       [97.65625603, 98.90130574, 86.64957427],
       [90.32836749, 86.64957427, 98.90130574]])

In [16]:
subs=utils.fileNameArray_to_SubmissionArray(arr_set1_tok,students)
clusterer=NCDClusterer([],subs)
sigmoid(1-clusterer.checkBlockSimilarity(k=10,b=1024,s=256))

array([[98.90130574, 96.51983383, 96.45653381],
       [96.51983383, 98.90130574, 96.50479626],
       [96.45653381, 96.50479626, 98.90130574]])

In [22]:
arr_set2=[r"C:\Users\vikram14\Desktop\Research\GradescopeFileSimilarities\set2\FuncallEval.java",
r"C:\Users\vikram14\Desktop\Research\GradescopeFileSimilarities\set2\FuncallEval1.java",
r"C:\Users\vikram14\Desktop\Research\GradescopeFileSimilarities\set2\FuncallEvaluator.java",
r"C:\Users\vikram14\Desktop\Research\GradescopeFileSimilarities\set2\FuncallEvaluator1.java"]
students= [("a",1),("b",2),("c",3),("d",4),("e",5)]
utils.deleteFiles()
arr_set2_tok,arr_set2_stripped=utils.tokenizeFiles(arr_set2)
subs=utils.fileNameArray_to_SubmissionArray(arr_set2_tok,students)
clusterer=NCDClusterer([],subs)
1-clusterer.checkBlockSimilarity(k=10,b=1024,s=256)
sigmoid(1-clusterer.checkBlockSimilarity(k=10,b=1024,s=256))


array([[98.90130574, 96.41001956, 96.18577697, 96.22359976],
       [96.41001956, 98.90130574, 96.17708272, 95.80381663],
       [96.18577697, 96.17708272, 98.90130574, 96.06248168],
       [96.22359976, 95.80381663, 96.06248168, 98.90130574]])

In [26]:
arr_set5=[r"C:\Users\vikram14\Desktop\Research\GradescopeFileSimilarities\set5\LessThanOrEqualEvaluator.java",
r"C:\Users\vikram14\Desktop\Research\GradescopeFileSimilarities\set5\MyLessThanEqualOperation.java",]
students= [("a",1),("b",2),("c",3),("d",4)]
utils.deleteFiles()
arr_set5_tok,arr_set5_stripped=utils.tokenizeFiles(arr_set5)
subs=utils.fileNameArray_to_SubmissionArray(arr_set5_tok,students)
clusterer=NCDClusterer([],subs)

1-clusterer.checkBlockSimilarity(k=10,b=256,s=64)
sigmoid(1-clusterer.checkBlockSimilarity(k=10,b=2048,s=512))


array([[98.90130574,  7.48693642],
       [ 7.48693642, 98.90130574]])

In [5]:
arr_set5_tok

['c:\\Users\\vikram14\\Desktop\\Research\\NCDBasedChecker\\test-files\\TokenizedCode\\LessThanOrEqualEvaluator.TOKENIZED.txt',
 'c:\\Users\\vikram14\\Desktop\\Research\\NCDBasedChecker\\test-files\\TokenizedCode\\MyLessThanEqualOperation.TOKENIZED.txt']

In [27]:
arr_set4=[r'C:\Users\vikram14\Desktop\Research\GradescopeFileSimilarities\set4\LambdaEvaluator.java',
            r'C:\Users\vikram14\Desktop\Research\GradescopeFileSimilarities\set4\LambdaEvaluator1.java']
students= [("a",1),("b",2)]
utils.deleteFiles()
arr_set4_tok,arr_set4_stripped=utils.tokenizeFiles(arr_set4)
subs=utils.fileNameArray_to_SubmissionArray(arr_set4_tok,students) 
clusterer=NCDClusterer([],subs)
1-clusterer.checkBlockSimilarity(k=10,b=256,s=64) 
sigmoid(1-clusterer.checkBlockSimilarity(k=10,b=1024,s=256))        

array([[98.90130574, 91.70110599],
       [91.70110599, 98.90130574]])

In [5]:
def sigmoid (x):
    return 1/(1+np.exp(-30*(x-0.85)))*100

In [23]:
arr_set3=[r'C:\Users\vikram14\Desktop\Research\GradescopeFileSimilarities\set3\NewEnvironment.java',
            r'C:\Users\vikram14\Desktop\Research\GradescopeFileSimilarities\set3\NewEnvironment1.java']
students= [("a",1),("b",2)]
utils.deleteFiles()
arr_set3_tok,arr_set3_stripped=utils.tokenizeFiles(arr_set3)
subs=utils.fileNameArray_to_SubmissionArray(arr_set3_tok,students) 
clusterer=NCDClusterer([],subs)
1-clusterer.checkBlockSimilarity(k=10,b=256,s=64) 
sigmoid(1-clusterer.checkBlockSimilarity(k=10,b=1024,s=256))    

array([[98.90130574, 89.85877888],
       [89.85877888, 98.90130574]])

In [24]:
arr_set3_tok

['c:\\Users\\vikram14\\Desktop\\Research\\NCDBasedChecker\\test-files\\TokenizedCode\\NewEnvironment.TOKENIZED.txt',
 'c:\\Users\\vikram14\\Desktop\\Research\\NCDBasedChecker\\test-files\\TokenizedCode\\NewEnvironment1.TOKENIZED.txt']